//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisUygulamaASP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSati
    {
        public int SatisID { get; set; }
        public Nullable<int> Urun { get; set; }
        public Nullable<byte> Personel { get; set; }
        public Nullable<int> Musteri { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
    
        public virtual tblMusteri tblMusteri { get; set; }
        public virtual tblPersonel tblPersonel { get; set; }
        public virtual tblUrun tblUrun { get; set; }
    }
}
